config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    resources :users
    resources :rooms, only: [:new, :create, :edit, :destroy, :update] do 
      resources :reservations
    end
  end

  devise_for :users
  root "rooms#index"
  resources :rooms, only: [:index, :show]
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room

  # validates :time_end, numericality: { greater_than: :time_start }
  
  STATES = %w{ active inactive }

  STATES.each do |state|
    define_method("#{state}?") do 
      self.state == state
    end

    define_method("#{state}!") do
      self.update_attribute(:state, state)
    end
  end
end

app/models/room.rb
class Room < ActiveRecord::Base

  @allow_value = %w(A B C D E F)
  validates :name, uniqueness: { scope: :area }, 
    numericality: { only_integer: true }
  validates :area, inclusion: { in: @allow_value }
  validates :capacity, numericality: { only_integer: true }
  validates :description, length: { minimum: 10 }
  validates :name, :area, :capacity, :description, presence: true

  has_many :reservations

  def self.search(search)
    where("name LIKE ? OR area LIKE ? OR capacity LIKE ?",
      "%#{search}", "%#{search}", "%#{search}")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reservations
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  
  def index
  end

  private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that"
    end
  end

end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < Admin::ApplicationController

  before_action :authenticate_user!
  before_action :teacher_only
  
  def new
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new
  end

  def create
    @reservation = current_user.reservations.build(reservation_params)
    @reservation.room_id = params[:room_id]

    reservations_of_specific_room = Reservation.where(room_id: @reservation.room_id, state: "active")
    date_of_specific_room = reservations_of_specific_room.map { |a| a.date }

    unless date_of_specific_room.include? @reservation.date
      @reservation.save
      redirect_to [:admin, current_user]
    else
      reservations_of_specific_room.each do |reser|
        unless (@reservation.time_start >= reser.time_end || 
          @reservation.time_end <= reser.time_start) && 
          (@reservation.time_start < @reservation.time_end)

          flash.now[:alert] = "Select another time"
          render "new"
          break
        else
          if reser == reservations_of_specific_room.last
            @reservation.save
            redirect_to [:admin, current_user]
          end          
        end
      end
    end

  end

  private

  def reservation_params
    params.require(:reservation).permit(:time_start, :time_end, :date)
  end

  def teacher_only
    if current_user.admin?
      redirect_to root_path, alert: "Only teachers can book classroom"
    end
  end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::ApplicationController

  before_action :authorize_admin!

  def new
    @room = Room.new
  end

  def create
    @room = Room.create(room_params)
    if @room.save
      flash[:notice] = "Room has been created."
      redirect_to room_path(@room)
    else
      flash.now[:alert] = "Room has not been created."
      render 'new'
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "Room has been updated."
      redirect_to room_path(@room)
    else
      flash[:alert] = "Room has not been updated."
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "Room #{@room.area + @room.name} has been deleted."
    redirect_to rooms_url
  end

  private

  def room_params
    params.require(:room).permit(:area, :name, :capacity, :description)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorize_admin!, only: [:new, :create]

  def index
    @users = User.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to [:admin, @user]
    else
      flash.now[:alert] = "User has not been updated."
      render "edit"
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "User #{@user.email} has been deleted"
    redirect_to [:admin, @user]
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end

  def set_user
    @user = User.find(params[:id])

     unless current_user.admin? || @user.id == current_user.id
      redirect_to root_path, alert: "You must be an admin to do that"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
    if params[:search]
      @rooms = Room.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
    else
      @rooms = Room.paginate(:page => params[:page], :per_page => 15)
    end
  end

  

  def show
    # @room = Room.find(params[:id])
  end

  private

  def room_params
    params.require(:room).permit(:area, :name, :capacity, :description)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
  def flash_message(key)
    {
      alert: 'alert-danger',
      notice: 'alert-info'
    }[key.to_sym] || key.to_s 
  end
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/application/index.html.erb
<div class="row" id="admin">
  <div class="col-md-9">
    <div class="page-header">
      <h1>Admin Lounge</h1>
    </div>
    <p>This is a place for admins</p>
  </div>

  <div class="col-md-3">
    <h2>Links</h2>
    <ul class="nav nav-stacked">
      <li><%= link_to "Users", admin_users_path %></li>
    </ul>
  </div>
</div>

app/views/admin/reservations/new.html.erb
<div class="page-header">
  <h1>New Reservation</h1>
</div>

<%= form_for [:admin, :room, @reservation] do |f| %>
  <p>
    <%= f.label :time_start %> <br>
    <%= f.time_select :time_start, { start_hour: 7, end_hour: 17, minute_step: 30 }, 
      { class: "form-control custom-form" } %>
  </p>

  <p>
    <%= f.label :time_end %> <br>
    <%= f.time_select :time_end, { start_hour: 8, end_hour: 20, minute_step: 30 },
      { class: "form-control custom-form" } %>
  </p>

  <p>
    <%= f.label :date %> <br>
    <%= f.date_select :date, { discard_year: true, order: [:day, :month] }, { class: "form-control custom-form" } %>
  </p>
  
  <%= f.submit class: "btn btn-primary" %>
  
<% end %> 

app/views/admin/rooms/_form.html.erb
<%= form_for [:admin, room] do |f| %>

  <p>
    <%= f.label :area %> <br>
    <%= f.select :area, options_for_select(['A', 'B', 'C', 'D', 'E', 'F']), 
    {}, class: "form-control" %>    
  </p>

  <p>
    <%= f.label :name %> <br>
    <%= f.number_field :name, class: "form-control" %>
  </p>

  <p>
    <%= f.label :capacity %> <br>
    <%= f.number_field :capacity, class: "form-control" %>
  </p>

  <p>
    <%= f.label :description %> <br>
    <%= f.text_field :description, class: "form-control" %>
  </p>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/rooms/edit.html.erb
<div class="page-header">
  <h1>Edit Room</h1>
</div>
<%= render "form", room: @room, admin: @user %>

app/views/admin/rooms/new.html.erb
<div class="page-header">
  <h1>New Room</h1>
</div>
<%= render "form", room: @room, admin: @user %>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, user] do |f| %>

  <p>
    <%= f.label :email %> <br>
    <%= f.email_field :email, class: "form-control" %>  
  </p>

  <p>
    <%= f.label :password %> <br>
    <%= f.password_field :password, class: "form-control" %> <br>
  </p>

  <p>
    <%= f.check_box :admin %>
    <%= f.label :admin, "Is an admin?"  %>
  </p>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <h1>Edit User</h1>
</div>

<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>

  <ul class="actions">
    <% if current_user.admin? %>
      <li>
        <%= link_to "New User", new_admin_user_path, class: "new" %>
      </li>
    <% end %>
  </ul>
</div>

<div class="row">
  <div class="col-md-6">
    <h3>Admins</h3>    
    <ul>
      <% @users.select { |user| user.admin? }.each do |user| %>
        <li><%= link_to user.email, [:admin, user] %></li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-6">
    <h3>Teachers</h3>    
    <ul>
      <% @users.select { |user| !user.admin? }.each do |user| %>
        <li><%= link_to user.email, [:admin, user] %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="page-header">
  <h1>New User</h1>
</div>

<%= render "form", user: @user %>

app/views/admin/users/show.html.erb
<div class="page-header">
  <h1><%= @user.email %></h1>
  <% if current_user.admin? || @user.id == current_user.id %>
    <ul class="actions">
      <li>
        <%= link_to "Edit User", edit_admin_user_path(@user), class: "edit" %>
      </li>

      <li>
        <%= link_to "Delete User", admin_user_path(@user), method: :delete,
        data: { confirm: "Are you sure?" }, class: "delete" %>
      </li>
    </ul>
  <% end %>  
</div>

<div class="page-header">
  <h3>Reservations</h3>
</div>

<table class="table table-hover table-striped table-bordered">
  <thead>
    <tr>
      <th>Index</th>
      <th>Room</th>
      <th>Time</th>
      <th>Date</th>
      <td>State</td>
    </tr>
  </thead>
  <tbody>
    <% @user.reservations.each_with_index do |reser, index| %>
      <tr data-link="<%= room_path(reser.room) %>">
        <td><%= index + 1%></td>
        <td><%= reser.room.area + reser.room.name %></td>
        <td><%= reser.time_start.strftime("%I:%M%p") %> - <%= reser.time_end.strftime("%I:%M%p") %></td>
        <td><%= reser.date.strftime("%d/%m/%Y") %></td>
        <td><%= reser.state %></td>
      </tr>
    <% end %>
 </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header", style="width: 100px">
        <%= link_to image_tag('Snorlax.png'), root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", "#" %></li>
          <li><%= link_to "Contact", "#" %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% unless user_signed_in? %>
            <li>
              <%= link_to "Sign in", new_user_session_path %>
            </li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", [:admin, current_user] %></li>
                <% if current_user.admin? %>
                  <li><%= link_to "Admin Lounge", admin_root_path %></li>
                <% end %>
                <li><%= link_to "Users list", admin_users_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              </ul> 
            </li>
          <% end %>
        </ul>
      </div>
    </div>  
  </nav>

  <div class="container">
    <% flash.each do |key, message| %>
      <div class="alert <%= flash_message(key) %>"><%= message %></div>
    <% end %>

    <%= yield %>

    <hr>

  </div>
  
  
  <footer>
    <p>&copy; 2016 House Lannister</p>
  </footer>
  
</body>
</html>

app/views/rooms/index.html.erb
<div class="page-header">
  <h1>Rooms</h1>
  <% if current_user.try(:admin?) %>
    <ul class="actions">
      <li>
        <%= link_to "New Room", new_admin_room_path, class: "new" %>
      </li>
    </ul>
  <% end %>
</div>

<%= form_tag(rooms_path, :method => "get", id: "custom-search-input") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Rooms", class: "form-control input-md" %>
  <%= button_tag(type: "submit", class: "btn btn-default") do %>
    <i class="glyphicon glyphicon-search"></i>
<% end %>
  
<% end %>

<% if @rooms.present? %>
  <table class="table table-hover table-striped table-bordered">
    <thead>
    <tr>
      <th>Index</th>
      <th>Area</th>
      <th>Name</th>
      <th>Capacity</th>
    </tr>
    </thead>
    <tbody>
    <% @rooms.each_with_index do |room, index| %>
      <tr data-link="<%= room_path(room) %>">
        <td><%= index + 1%></td>
        <td><%= room.area %></td>
        <td><%= room.name %></td>
        <td><%= room.capacity %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @rooms, renderer: BootstrapPagination::Rails %>
<% else %>
  <p>There are no rooms containing the term(s) <%= params[:search] %></p>
<% end %>

app/views/rooms/show.html.erb
<div class="page-header">
  <h1>Room <%= @room.area + @room.name %></h1>
  <% if current_user.try(:admin?) %>
    <ul class="actions">
      <li>
        <%= link_to "Edit Room", edit_admin_room_path(@room), class: "edit" %>
      </li>

      <li>
        <%= link_to "Delete Room", admin_room_path(@room), method: :delete, 
        data: { confirm: "Are you sure?" }, class: "delete" %>
      </li>
    </ul>
  <% end %>
  
  <% if user_signed_in? && !current_user.try(:admin?) %>
    <ul class="actions">
      <li>
        <%= link_to "Book now", new_admin_room_reservation_path(@room), class: "new" %>
      </li>
    </ul>  
  <% end %>
 </div> 

<p>Capacity: <%= @room.capacity %></p>
<p>Description: <%= @room.description %></p>